#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="$ROOT_DIR/packages/contracts"
WEB_DIR="$ROOT_DIR/apps/web"

# Default to Base mainnet RPC
DEFAULT_FORK_URL="https://mainnet.base.org"
ANON_TOKEN="0x0Db510e79909666d6dEc7f5e49370838c16D950f"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}   AnonPool Local Development Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check dependencies
check_dependency() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}Error: $1 is not installed${NC}"
        echo "Please install $1 first"
        exit 1
    fi
}

echo "Checking dependencies..."
check_dependency "anvil"
check_dependency "forge"
check_dependency "cast"
check_dependency "bun"
echo -e "${GREEN}✓ All dependencies found${NC}"
echo ""

# Parse arguments
FORK_URL="$DEFAULT_FORK_URL"
FORK_BLOCK=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --fork)
            FORK_URL="$2"
            shift 2
            ;;
        --fork-block)
            FORK_BLOCK="$2"
            shift 2
            ;;
        --help)
            echo "Usage: ./scripts/local-dev.sh [options]"
            echo ""
            echo "Options:"
            echo "  --fork <rpc-url>      Fork from a specific RPC (default: Base mainnet)"
            echo "  --fork-block <num>    Fork from specific block number"
            echo "  --help                Show this help message"
            echo ""
            echo "Examples:"
            echo "  ./scripts/local-dev.sh                           # Fork Base mainnet"
            echo "  ./scripts/local-dev.sh --fork https://sepolia.base.org  # Fork Base Sepolia"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Build Anvil command - always fork Base mainnet by default
ANVIL_CMD="anvil --host 0.0.0.0 --fork-url $FORK_URL"

echo -e "${YELLOW}Forking from: $FORK_URL${NC}"
if [ -n "$FORK_BLOCK" ]; then
    ANVIL_CMD="$ANVIL_CMD --fork-block-number $FORK_BLOCK"
    echo -e "${YELLOW}At block: $FORK_BLOCK${NC}"
fi

echo ""

# Kill any existing Anvil process
if pgrep -x "anvil" > /dev/null; then
    echo "Stopping existing Anvil process..."
    pkill -x "anvil" || true
    sleep 1
fi

# Start Anvil in background
echo "Starting Anvil..."
$ANVIL_CMD &> /tmp/anvil.log &
ANVIL_PID=$!

# Wait for Anvil to be ready
echo "Waiting for Anvil to start..."
for i in {1..30}; do
    if cast chain-id --rpc-url http://127.0.0.1:8545 &> /dev/null; then
        break
    fi
    sleep 0.5
done

if ! cast chain-id --rpc-url http://127.0.0.1:8545 &> /dev/null; then
    echo -e "${RED}Failed to start Anvil${NC}"
    cat /tmp/anvil.log
    exit 1
fi

CHAIN_ID=$(cast chain-id --rpc-url http://127.0.0.1:8545)
echo -e "${GREEN}✓ Anvil running (Chain ID: $CHAIN_ID, PID: $ANVIL_PID)${NC}"
echo ""

# Deploy contracts
echo "Deploying contracts..."
cd "$CONTRACTS_DIR"

# Run deployment and capture output
DEPLOY_OUTPUT=$(forge script script/DeployLocal.s.sol:DeployLocal \
    --rpc-url http://127.0.0.1:8545 \
    --broadcast \
    2>&1)

echo "$DEPLOY_OUTPUT"

# Extract addresses from output
POOL_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "AnonPool:" | awk '{print $2}')
AUCTION_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "AuctionSpender:" | awk '{print $2}')

if [ -z "$POOL_ADDRESS" ]; then
    echo -e "${RED}Failed to extract contract addresses${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}   Deployment Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Create/update .env.local for the web app
ENV_FILE="$WEB_DIR/.env.local"
ENV_CONTENT="# Local Development Configuration (Base mainnet fork)
# Generated by scripts/local-dev.sh at $(date)

NEXT_PUBLIC_TESTNET=true
NEXT_PUBLIC_TESTNET_RPC_URL=http://127.0.0.1:8545
NEXT_PUBLIC_POOL_CONTRACT=$POOL_ADDRESS
NEXT_PUBLIC_AUCTION_CONTRACT=$AUCTION_ADDRESS

# Using real \$ANON token from Base mainnet
# ANON_TOKEN=$ANON_TOKEN

# Add your API keys below
# NEYNAR_API_KEY=
# NEYNAR_SIGNER_UUID=
# UPLOAD_API_KEY=
"

echo -e "${YELLOW}Creating $ENV_FILE...${NC}"
echo "$ENV_CONTENT" > "$ENV_FILE"
echo -e "${GREEN}✓ Environment file created${NC}"
echo ""

# Print summary
echo -e "${BLUE}Contract Addresses:${NC}"
echo "  \$ANON:    $ANON_TOKEN (real token from Base mainnet)"
echo "  Pool:     $POOL_ADDRESS"
echo "  Auction:  $AUCTION_ADDRESS"
echo ""
echo -e "${BLUE}Anvil Info:${NC}"
echo "  RPC URL:  http://127.0.0.1:8545"
echo "  Chain ID: $CHAIN_ID"
echo "  PID:      $ANVIL_PID"
echo ""
echo -e "${BLUE}Test Account (Account #0):${NC}"
echo "  Address:  0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
echo "  Key:      0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
echo "  Balance:  1,000,000 TEST tokens + 10,000 ETH"
echo ""

echo -e "${YELLOW}To start the frontend:${NC}"
echo "  cd apps/web && bun run dev"
echo ""
echo -e "${YELLOW}To stop Anvil:${NC}"
echo "  kill $ANVIL_PID"
echo ""
echo -e "${YELLOW}Anvil logs:${NC}"
echo "  tail -f /tmp/anvil.log"
echo ""

# Keep script running and show Anvil output
echo -e "${GREEN}Anvil is running in the background. Press Ctrl+C to stop.${NC}"
echo ""

# Trap Ctrl+C to clean up
trap "echo ''; echo 'Stopping Anvil...'; kill $ANVIL_PID 2>/dev/null; exit 0" INT

# Follow Anvil logs
tail -f /tmp/anvil.log
